#!/bin/sh

###########################################
# Build script for package builder
# Just for simplify! =)
# $Id: build,v 1.3 2007/09/10 00:53:58 i27249 Exp $
###########################################
qmake
make -j2
strip packagebuilder
cp packagebuilder /usr/bin/
cp packagebuilder_ru.qm /usr/share/mpkg/
echo "Package builder: build complete"

