#!/bin/sh

###########################################
# Build script for package builder
# Just for simplify! =)
# $Id: build,v 1.1 2007/05/16 01:38:32 i27249 Exp $
###########################################
make -j2
strip packagebuilder
cp packagebuilder /usr/local/bin/
echo "Package builder: build complete"

