######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 19 07:51:20 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += package_builder.ui
SOURCES += main.cpp mainwindow.cpp
