######################################################################
# Automatically generated by qmake (2.01a) ?? ????? 15 12:37:20 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += package_builder.ui
SOURCES += main.cpp mainwindow.cpp
