######################################################################
# Automatically generated by qmake (2.01a) Thu Feb 15 14:27:42 2007
######################################################################

TEMPLATE = app
QMAKESPEC = macx-g++
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += package_builder.ui
SOURCES += main.cpp mainwindow.cpp
