######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 14 13:27:01 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += package_builder.ui
SOURCES += main.cpp mainwindow.cpp
