#ifndef ACTIONS_H_
#define ACTIONS_H_

#define ACT_INSTALL	0x01
#define ACT_REMOVE	0x02
#define ACT_CLEAN	0x04
#define ACT_SEARCH	0x05
#define ACT_UPGRADE	0x06
#define ACT_UPDATE	0x07
#define ACT_LIST	0x08
#define ACT_NONE	0x09
#define ACT_INDEX	0x0a
#define ACT_PURGE	0x0b
#define ACT_CONVERT	0x0c
#define ACT_CONVERT_DIR	0x0d
#define ACT_LIST_REP	0x0e
#define ACT_TAG		0x0f
#define ACT_TEST	0x10
#define ACT_COMMIT	0x11
#define ACT_SHOWQUEUE	0x12
#define ACT_RESETQUEUE	0x13
#define ACT_SHOW	0x14
#define ACT_INSTALLFROMLIST 0x15
#define ACT_PACKAGEMENU 0x16
#define ACT_CHECKDAMAGE 0x17
#define ACT_CONFIG	0x18
#define ACT_EXPORT	0x19
#define ACT_GENDEPS	0x1a
#define ACT_FILESEARCH  0x1b
#define ACT_WHICH	0x1c
#define ACT_INSTALLGROUP 0x1d
#define ACT_LISTGROUP	0x1e
#define ACT_REMOVEGROUP 0x1f
#define ACT_LISTDEPENDANTS 0x20
#define ACT_REINSTALL	0x21
#endif

