#!/bin/sh

#######################################################
# Build script for manager
# Just to simplify =)
# $Id: build,v 1.9 2007/11/21 01:57:53 i27249 Exp $
#######################################################
export QTDIR=/opt/qt4
export PATH=$QTDIR/bin:$PATH
qmake
make -j2 || exit 1
strip manager
cp manager /usr/bin/
mkdir -p /usr/share/mpkg/
cp -R icons /usr/share/mpkg/
cp splash.png /usr/share/mpkg/
cp *.qm /usr/share/mpkg/
cp applink/* /usr/share/applications/
echo "Manager: build complete"
exit 0