#!/bin/sh

#######################################################
# Build script for manager
# Just to simplify =)
# $Id: build,v 1.4 2007/05/21 18:35:55 i27249 Exp $
#######################################################
make -j2
strip manager
cp manager /usr/local/bin/
mkdir -p /usr/share/mpkg/
cp -R icons /usr/share/mpkg/
cp splash.png /usr/share/mpkg/
cp *.qm /usr/share/mpkg/
echo "Manager: build complete"

