#!/bin/sh

#######################################################
# Build script for manager
# Just to simplify =)
# $Id: build,v 1.8 2007/10/23 22:43:55 i27249 Exp $
#######################################################
export QTDIR=/opt/qt4
export PATH=$QTDIR/bin:$PATH
qmake
make -j2
strip manager
cp manager /usr/bin/
mkdir -p /usr/share/mpkg/
cp -R icons /usr/share/mpkg/
cp splash.png /usr/share/mpkg/
cp *.qm /usr/share/mpkg/
cp applink/* /usr/share/applications/
echo "Manager: build complete"

