######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 16 09:19:56 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += aboutbox.h mainwindow.h preferencesbox.h
FORMS += aboutbox.ui pkgmanager.ui preferencesbox.ui
SOURCES += aboutbox.cpp main.cpp mainwindow.cpp preferencesbox.cpp
