#!/bin/sh

###################################################
# Build script over entire project
# Performs clean build of all items
# $Id: build_all,v 1.4 2007/11/21 01:57:53 i27249 Exp $
###################################################

(cd src/build || exit 1; ./clean; ./build || exit 1)
(cd manager || exit 1; make clean; ./build || exit 1)
(cd packagebuilder || exit 1; make clean; ./build || exit 1)
(cd updatechecker || exit 1; make clean; ./build || exit 1)
(cd installer || exit 1; ./clean; ./build || exit 1)
echo "Build finished."
