#!/bin/sh

#########################################################
# Script to initalize directory structure, and create
# a default environment.
# Script is linux-oriented, if you use MacOSX, please
# write your own (just change paths).
# Use at development, not in real installations.
# 
# $Id: init_structure,v 1.1 2007/05/16 01:38:32 i27249 Exp $
#
#########################################################
mkdir -p /root/development/sys_cache/
mkdir -p /var/log/mpkg/backup
mkdir -p /var/log/mpkg/scripts
(cd src; make sqlclean)
cp src/mpkg.xml /etc/
cp manager/groups.xml /etc/mpkg-groups.xml
echo "Environment set up correctly"

