#!/bin/sh

#########################################################
# Script to initalize directory structure, and create
# a default environment.
# Script is linux-oriented, if you use MacOSX, please
# write your own (just change paths).
# Use at development, not in real installations.
# 
# $Id: init_structure,v 1.2 2007/06/02 23:26:06 i27249 Exp $
#
#########################################################
mkdir -p /var/mpkg/cache
mkdir -p /var/mpkg/backup
mkdir -p /var/mpkg/scripts
(cd src; make sqlclean)
cp src/mpkg.xml /etc/
cp manager/groups.xml /etc/mpkg-groups.xml
echo "Environment set up correctly"

