#!/bin/sh
echo "clearing old build"
rm -rf out_packages/lib
rm -rf out_packages/console
rm -rf out_packages/tools
rm -rf out_packages/gui
rm -rf out_packages/*.tgz

echo "Creating library package"
mkdir -p out_packages/lib/install
cp pkg_descriptions/lib/*  out_packages/lib/install/
mkdir -p out_packages/lib/usr/lib
mkdir -p out_packages/lib/usr/include
mkdir -p out_packages/lib/etc
mkdir -p out_packages/lib/usr/share/locale/ru/LC_MESSAGES
cp -R /usr/include/mpkg out_packages/lib/usr/include/
#cp src/mpkg.xml out_packages/lib/etc/
cp manager/groups.xml out_packages/lib/etc/mpkg-groups.xml
cp src/mpkg-remove-blacklist out_packages/lib/etc/
cp /usr/lib/libmpkg* out_packages/lib/usr/lib/
cp /usr/share/locale/ru/LC_MESSAGES/installpkg-ng.mo out_packages/lib/usr/share/locale/ru/LC_MESSAGES/
cd out_packages/lib/; buildpkg; mv *.tgz ..; cd ../..

echo "Creating console package"
./generate_man
mkdir -p out_packages/console/install
cp  pkg_descriptions/console/* out_packages/console/install
mkdir -p out_packages/console/usr/bin
cp /usr/bin/mpkg out_packages/console/usr/bin/
(cd out_packages/console/usr/bin; ln -s mpkg buildpkg)
(cd out_packages/console/usr/bin; ln -s mpkg buildsrcpkg)
mkdir -p out_packages/console/usr/man/ru/man8
mkdir -p out_packages/console/usr/man/man8
cp mpkg.8.en out_packages/console/usr/man/man8/mpkg.8
cp mpkg.8.ru out_packages/console/usr/man/ru/man8/mpkg.8
cd out_packages/console/; buildpkg; mv *.tgz ..; cd ../..

echo "Creating GUI package"
mkdir -p out_packages/gui/install
cp  pkg_descriptions/gui/*  out_packages/gui/install/
mkdir -p out_packages/gui/usr/bin
mkdir -p out_packages/gui/usr/share/applications
cp /usr/bin/manager out_packages/gui/usr/bin/
cp /usr/bin/updatechecker out_packages/gui/usr/bin/
cp -R /usr/share/mpkg out_packages/gui/usr/share/mpkg

cp -R manager/applink/* out_packages/gui/usr/share/applications/
cd out_packages/gui/; buildpkg; mv *.tgz ..; cd ../..

echo "Creating tools package"
mkdir -p out_packages/tools/install
cp  pkg_descriptions/tools/* out_packages/tools/install/
mkdir -p out_packages/tools/usr/bin
mkdir -p out_packages/tools/usr/share/mpkg
cp /usr/share/mpkg/packagebuilder out_packages/tools/usr/share/mpkg/
cp /usr/bin/packagebuilder out_packages/tools/usr/bin/

cd out_packages/tools; buildpkg; mv *.tgz ..; cd ../..

echo "All packages created successfully"


