#!/bin/sh
echo "clearing old build"
rm -rf out_packages/lib
rm -rf out_packages/console
rm -rf out_packages/tools
rm -rf out_packages/gui
rm -rf out_packages/*.tgz

echo "Creating library package"
mkdir -p out_packages/lib/install
cp pkg_descriptions/lib/*  out_packages/lib/install/
mkdir -p out_packages/lib/usr/local/lib
mkdir -p out_packages/lib/usr/local/include
mkdir -p out_packages/lib/etc
mkdir -p out_packages/lib/usr/share/locale/ru/LC_MESSAGES
cp -R /usr/local/include/mpkg out_packages/lib/usr/local/include/
cp src/mpkg.xml out_packages/lib/etc/
cp manager/groups.xml out_packages/lib/etc/mpkg-groups.xml
cp src/mpkg-remove-blacklist out_packages/lib/etc/
cp /usr/local/lib/libmpkg* out_packages/lib/usr/local/lib/
cp /usr/share/locale/ru/LC_MESSAGES/installpkg-ng.mo out_packages/lib/usr/share/locale/ru/LC_MESSAGES/
cd out_packages/lib/; buildpkg; mv *.tgz ..; cd ../..

echo "Creating console package"
mkdir -p out_packages/console/install
cp  pkg_descriptions/console/* out_packages/console/install
mkdir -p out_packages/console/usr/local/bin
cp /usr/local/bin/mpkg out_packages/console/usr/local/bin/
(cd out_packages/console/usr/local/bin; ln -s mpkg buildpkg)
cd out_packages/console/; buildpkg; mv *.tgz ..; cd ../..

echo "Creating GUI package"
mkdir -p out_packages/gui/install
cp  pkg_descriptions/gui/*  out_packages/gui/install/
mkdir -p out_packages/gui/usr/local/bin
mkdir -p out_packages/gui/usr/share/applications
cp /usr/local/bin/manager out_packages/gui/usr/local/bin/
cp /usr/local/bin/updatechecker out_packages/gui/usr/local/bin/
cp -R /usr/share/mpkg out_packages/gui/usr/share/mpkg

cp -R manager/applink/* out_packages/gui/usr/share/applications/
cd out_packages/gui/; buildpkg; mv *.tgz ..; cd ../..

echo "Creating tools package"
mkdir -p out_packages/tools/install
cp  pkg_descriptions/tools/* out_packages/tools/install/
mkdir -p out_packages/tools/usr/local/bin
cp /usr/local/bin/packagebuilder out_packages/tools/usr/local/bin/
cd out_packages/tools; buildpkg; mv *.tgz ..; cd ../..

echo "All packages created successfully"


