#!/bin/sh
# Build script for update checker
# Just for simplify the deals
# $Id: build,v 1.1 2007/05/16 01:38:32 i27249 Exp $

make -j2 && strip updatechecker && cp updatechecker /usr/local/bin/
echo "Update monitor: build complete"

