#!/bin/sh
# Build script for update checker
# Just for simplify the deals
# $Id: build,v 1.2 2007/08/21 18:05:22 i27249 Exp $

qmake && make -j2 && strip updatechecker && cp updatechecker /usr/local/bin/
echo "Update monitor: build complete"

