######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 16 03:32:13 2007
######################################################################
TRANSLATIONS=updatechecker_ru.ts
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += monitor.h trayapp.h
SOURCES += main.cpp monitor.cpp trayapp.cpp
LIBS+= -lmpkg
INCPATH+= /usr/include/libxml2

